# Generated by Django 5.0.1 on 2024-10-12 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("favorite", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favoriteartwork",
            old_name="favorited_recipe",
            new_name="favorited_artwork",
        ),
    ]
