FROM node:16-alpine as build


WORKDIR /app
COPY package*.json ./
ARG REACT_APP_API_URL=https://tesseramosaic.art
ARG VER=1
ENV REACT_APP_API_URL=https://tesseramosaic.art
RUN echo "API URL prefix: ${REACT_APP_API_URL}"
RUN npm ci
COPY . ./
RUN npm run build
CMD cp -r build result_build
