FROM node:16-alpine as build


WORKDIR /app
COPY package*.json ./
ENV REACT_APP_API_URL=https://tessera.hopto.org/
RUN echo "API URL prefix: ${REACT_APP_API_URL}"
RUN npm ci
COPY . ./
RUN npm run build
CMD cp -r build result_build
