FROM node:16-alpine as build


WORKDIR /app
COPY package*.json ./
ARG REACT_APP_API_URL=http://localhost:8000/
ENV REACT_APP_API_URL=http://localhost:8000/
RUN echo "API URL prefix: ${REACT_APP_API_URL}"
RUN npm ci
COPY . ./
RUN npm run build
CMD cp -r build result_build
