# Generated by Django 5.0.1 on 2024-06-30 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailMainForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("phone_num", models.CharField(max_length=25)),
                ("comment", models.TextField(blank=True, max_length=150)),
                ("contact_consent", models.BooleanField(default=False)),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GiftCert",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                2000, "Минимальная стоимость сертификата2000 тенге"
                            )
                        ]
                    ),
                ),
                ("name_sender", models.CharField(max_length=50)),
                ("email_sender", models.EmailField(max_length=50)),
                ("name_recepient", models.CharField(max_length=50)),
                ("email_recipient", models.EmailField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued"),
                            ("REDEEMED", "Redeemed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ISSUED",
                        max_length=10,
                    ),
                ),
                ("date_issued", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
