# Generated by Django 5.0.1 on 2025-01-31 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcert",
            name="amount",
            field=models.PositiveBigIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        2000, "Минимальная стоимость сертификата2000 тенге"
                    ),
                    django.core.validators.MaxValueValidator(
                        500000, "Максимальная стоимость сертификата500000 тенге"
                    ),
                ]
            ),
        ),
    ]
