# Generated by Django 4.1.6 on 2023-07-25 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackrequest",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
