# Generated by Django 4.1.6 on 2023-03-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='contact_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='comment',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
