# Generated by Django 5.0.1 on 2024-01-27 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm_app", "0002_feedbackrequest_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="giftcert",
            old_name="date_created",
            new_name="date_issued",
        ),
    ]
