# Generated by Django 4.1.6 on 2023-03-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_rename_feedback_request_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='contact',
            new_name='phone_num',
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
