# Generated by Django 4.1.6 on 2023-06-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_rename_request_feedback_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMainForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone_num', models.CharField(max_length=25)),
                ('comment', models.TextField(blank=True, max_length=150)),
                ('contact_consent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCert',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('amount', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('REDEEMED', 'Redeemed')], default='ISSUED', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback_request',
        ),
    ]
