# Generated by Django 4.1.6 on 2023-06-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_emailmainform_feedbackrequest_giftcert_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcert',
            old_name='email',
            new_name='email_recipient',
        ),
        migrations.RenameField(
            model_name='giftcert',
            old_name='name',
            new_name='name_sender',
        ),
        migrations.AddField(
            model_name='giftcert',
            name='email_sender',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcert',
            name='name_recepient',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
