# Generated by Django 4.1.6 on 2023-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_rename_email_giftcert_email_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcert',
            name='name_recepient',
            field=models.CharField(max_length=50),
        ),
    ]
