# Generated by Django 4.1.6 on 2023-06-04 14:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_alter_giftcert_name_recepient'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcert',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 6, 4, 14, 34, 4, 231598, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftcert',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000, 'Минимальная стоимость сертификата2000 тенге')]),
        ),
        migrations.AlterField(
            model_name='giftcert',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired')], default='ISSUED', max_length=10),
        ),
    ]
