# Generated by Django 4.1.6 on 2023-04-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Hyperlink')),
                ('text', models.CharField(max_length=100, verbose_name='Text on banner')),
                ('button', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('carousel_type', models.CharField(choices=[('MAIN', 'Main carousel'), ('GALLERY', 'Gallery carousel')], max_length=20)),
                ('image', models.ImageField(upload_to='carousel_items/')),
            ],
        ),
    ]
