# Generated by Django 4.1.6 on 2023-06-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Hyperlink')),
                ('text', models.CharField(max_length=100, verbose_name='Text on banner')),
                ('button', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(default=None, upload_to='carousel_items/')),
            ],
        ),
        migrations.DeleteModel(
            name='CarouselItem',
        ),
    ]
