# Generated by Django 4.1.6 on 2023-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_maincarouselitem_delete_carouselitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincarouselitem',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='Header on the banner'),
        ),
    ]
