# Generated by Django 4.1.6 on 2023-06-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_maincarouselitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincarouselitem',
            name='text',
            field=models.CharField(max_length=250, verbose_name='Text on banner'),
        ),
        migrations.AlterField(
            model_name='maincarouselitem',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Header on the banner'),
        ),
    ]
