# Generated by Django 4.1.6 on 2023-02-18 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='masterclass.masterclass')),
            ],
        ),
    ]
