# Generated by Django 4.1.6 on 2023-08-02 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_reservationadmin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "Booking by a registered user",
                "verbose_name_plural": "Bookings by registered users",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationadmin",
            options={
                "verbose_name": "A reservation made by an admin",
                "verbose_name_plural": "Reservations made by admins",
            },
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="attending",
            new_name="masterclass",
        ),
    ]
