# Generated by Django 5.0.1 on 2024-07-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "booking",
            "0006_alter_booking_options_alter_reservationadmin_options_and_more",
        ),
        ("masterclass", "0024_alter_masterclasstype_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(max_length=30)),
                ("guest_phone", models.CharField(max_length=15)),
                ("guest_consent", models.BooleanField()),
                (
                    "attending",
                    models.ForeignKey(
                        help_text="the course this guests is going to attend",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_reservations",
                        to="masterclass.masterclass",
                        verbose_name="course/masterclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "A reservation made by an admin",
                "verbose_name_plural": "Reservations made by admins",
            },
        ),
        migrations.DeleteModel(
            name="ReservationAdmin",
        ),
    ]
