# Generated by Django 5.0.1 on 2024-11-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_rename_available_storeitem_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeitemimage",
            name="store_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="images",
                to="store.storeitem",
            ),
            preserve_default=False,
        ),
    ]
