# Generated by Django 5.0.1 on 2024-12-05 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_storeitemimage_store_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.storeitem",
            ),
            preserve_default=False,
        ),
    ]
