# Generated by Django 5.0.1 on 2024-12-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0008_remove_artwork_is_replica_available_and_more"),
        ("store", "0004_basket_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="artwork",
        ),
        migrations.RemoveField(
            model_name="basket",
            name="item",
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.basket"
            ),
        ),
        migrations.CreateModel(
            name="BasketArtwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_reproduction", models.BooleanField()),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gallery.artwork",
                    ),
                ),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.basket"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basket",
            name="artwork",
            field=models.ManyToManyField(
                through="store.BasketArtwork", to="gallery.artwork"
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="item",
            field=models.ManyToManyField(
                through="store.BasketItem", to="store.storeitem"
            ),
        ),
    ]
