# Generated by Django 4.1.6 on 2023-06-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('author_type', models.CharField(choices=[('УЧЕНИК', 'УЧЕНИК'), ('ПРЕПОДАВАТЕЛЬ', 'ПРЕПОДАВАТЕЛЬ')], max_length=15)),
                ('image', models.ImageField(default=None, upload_to='carousel_items/')),
                ('is_on_main', models.BooleanField()),
                ('is_for_sale', models.BooleanField()),
                ('price', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
