# Generated by Django 4.1.6 on 2023-06-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_artwork_author_type_alter_artwork_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
