# Generated by Django 4.1.6 on 2023-06-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_artwork_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
