# Generated by Django 4.1.6 on 2023-06-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_artwork_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_on_main',
        ),
        migrations.AddField(
            model_name='artworkmainpage',
            name='is_on_main',
            field=models.BooleanField(default=True),
        ),
    ]
