# Generated by Django 4.1.6 on 2023-06-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_artwork_is_on_main_artworkmainpage_is_on_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkmainpage',
            name='is_on_main',
        ),
    ]
