# Generated by Django 5.0.1 on 2024-10-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0008_alter_artwork_author_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Artwork",
            new_name="LegacyArtwork",
        ),
    ]
