# Generated by Django 4.1.6 on 2023-02-18 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masterclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='masterclass', max_length=50, verbose_name='Title')),
                ('price', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, "Price can't be negative")])),
                ('currency', models.CharField(max_length=20)),
                ('time_begin', models.DateTimeField()),
                ('address', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Masterclass',
                'verbose_name_plural': 'Masterclasses',
                'ordering': ['-time_begin'],
            },
        ),
        migrations.CreateModel(
            name='MasterclassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(max_length=15, verbose_name='Link')),
                ('max_guests', models.PositiveSmallIntegerField(verbose_name='Max number of guests')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='How many hours required to finish the masterclass')),
                ('short_description', models.CharField(max_length=50, verbose_name='Short description')),
                ('full_description', models.TextField(blank=True, verbose_name='Full description')),
            ],
            options={
                'verbose_name': 'Masterclass type',
                'verbose_name_plural': 'Masterclass types',
            },
        ),
    ]
