# Generated by Django 4.1.6 on 2023-02-25 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0004_alter_masterclass_time_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='time_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='time_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
