# Generated by Django 4.1.6 on 2023-03-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0008_masterclass_num_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='num_of_guests',
        ),
    ]
