# Generated by Django 4.1.6 on 2023-04-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0009_remove_masterclass_num_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclasstype',
            name='image',
            field=models.ImageField(blank=True, upload_to='masterclasses/'),
        ),
    ]
