# Generated by Django 4.1.6 on 2023-08-06 18:16

from django.conf import settings
from django.db import migrations, models

import masterclass.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("masterclass", "0011_alter_masterclass_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterclass",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=models.SET(
                    masterclass.models.get_or_create_dummy_teacher),
                related_name="masterclasses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
