# Generated by Django 5.0.1 on 2024-01-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0015_alter_masterclasstype_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterclass",
            name="currency",
            field=models.CharField(
                choices=[("₸", "тенге"), ("₽", "рубли"), ("€", "евро")],
                default="тенге",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="masterclass",
            name="time_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="masterclass",
            name="time_start",
            field=models.DateTimeField(),
        ),
    ]
