# Generated by Django 5.0.1 on 2024-06-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0016_alter_masterclass_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterclasstype",
            name="short_description",
            field=models.CharField(max_length=230, verbose_name="Short description"),
        ),
    ]
