# Generated by Django 5.0.1 on 2024-02-16 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0016_alter_masterclass_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Tag"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MasterclassTypeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="masterclass.category",
                    ),
                ),
                (
                    "masterclass_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masterclass.masterclass",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="masterclasstypecategory",
            constraint=models.UniqueConstraint(
                fields=("category", "masterclass_type"),
                name="unique category-masterclass pair",
            ),
        ),
    ]
