# Generated by Django 5.0.1 on 2024-02-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0018_alter_masterclasstypecategory_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-id"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="masterclasstypecategory",
            options={"verbose_name_plural": "Masterclass Type Categories"},
        ),
        migrations.AddField(
            model_name="masterclasstypecategory",
            name="category_list",
            field=models.CharField(
                choices=[
                    ("FOR_WHOM", "For whom ths course"),
                    ("LENGTH", "Length"),
                    ("EXP", "Required or recommended experience"),
                    ("STYLE", "Style of mosaic"),
                ],
                default="FOR_WHOM",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
