# Generated by Django 5.0.1 on 2024-02-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0019_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="masterclasstypecategory",
            name="category_list",
        ),
        migrations.AddField(
            model_name="category",
            name="category_filter",
            field=models.CharField(
                choices=[
                    ("FOR_WHOM", "For whom ths course"),
                    ("LENGTH", "Length"),
                    ("EXP", "Required or recommended experience"),
                    ("STYLE", "Style of mosaic"),
                ],
                default="FOR_WHOM",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Name"),
        ),
    ]
