# Generated by Django 5.0.1 on 2024-02-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0020_remove_masterclasstypecategory_category_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterclasstype",
            name="category",
            field=models.ManyToManyField(
                through="masterclass.MasterclassTypeCategory", to="masterclass.category"
            ),
        ),
    ]
