# Generated by Django 5.0.1 on 2024-05-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0021_masterclasstype_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterclassFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "category_filter",
                    models.CharField(
                        choices=[
                            ("ORDER", "Specific fields for ordering queryset results"),
                            ("EXP", "Required or recommended experience"),
                            (
                                "DURATION",
                                "Duration of the masterclass: daily, multiple days, etc.",
                            ),
                            ("TARGET_AUDIENCE", "Target audience of the course"),
                            ("STYLE", "Style of mosaic"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["-id"],
            },
        ),
        migrations.AlterField(
            model_name="masterclasstype",
            name="category",
            field=models.ManyToManyField(
                through="masterclass.MasterclassTypeCategory",
                to="masterclass.masterclassfilter",
            ),
        ),
        migrations.AlterField(
            model_name="masterclasstypecategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="masterclass.masterclassfilter",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
