# Generated by Django 5.0.1 on 2024-05-11 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "masterclass",
            "0022_masterclassfilter_alter_masterclasstype_category_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MasterclassFilter",
            new_name="MasterclassCategory",
        ),
    ]
