# Generated by Django 5.0.1 on 2024-07-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0023_rename_masterclassfilter_masterclasscategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterclasstype",
            name="short_description",
            field=models.CharField(max_length=230, verbose_name="Short description"),
        ),
    ]
