# Generated by Django 5.0.1 on 2024-08-25 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0017_alter_masterclasstype_short_description"),
        ("masterclass", "0024_alter_masterclasstype_short_description"),
    ]

    operations = []
