# Generated by Django 5.0.1 on 2025-01-17 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterclass", "0025_merge_20240825_2239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterclasstype",
            name="duration",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0.5, "It cannot be shorter than 30 minutes"
                    )
                ],
                verbose_name="How many hours required to finish the masterclass",
            ),
        ),
    ]
