# Generated by Django 4.1.6 on 2023-03-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_rename_inquiry_feedback_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback_request',
            new_name='Request',
        ),
    ]
