# Generated by Django 4.1.6 on 2023-03-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_rename_contact_request_phone_num_alter_request_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Feedback_request',
        ),
    ]
