# Generated by Django 4.1.3 on 2022-11-22 10:28

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
