# Generated by Django 4.1.6 on 2023-02-17 04:33

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=mdeditor.fields.MDTextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
