# Generated by Django 4.1.6 on 2023-03-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_approach_school_question_school_review_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='logo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='Add or change the school name', max_length=20, verbose_name='School name '),
        ),
    ]
