# Generated by Django 5.0.1 on 2024-12-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0001_initial"),
        ("gallery", "0007_alter_artworkimage_artwork"),
        ("store", "0003_alter_storeitemimage_store_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="artwork",
        ),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(
                through="checkout.OrderItem", to="store.storeitem"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="checkout.order"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="store_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="store.storeitem",
            ),
        ),
        migrations.CreateModel(
            name="OrderArtwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to="gallery.artwork",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="checkout.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="artwork",
            field=models.ManyToManyField(
                through="checkout.OrderArtwork", to="gallery.artwork"
            ),
        ),
    ]
