# Generated by Django 5.0.1 on 2024-12-05 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_remove_orderitem_artwork_order_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
    ]
