# Generated by Django 5.0.1 on 2024-12-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0003_remove_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderartwork",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
