# Generated by Django 5.0.1 on 2024-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0004_orderartwork_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderartwork",
            name="quantity",
        ),
        migrations.AddField(
            model_name="orderartwork",
            name="is_reproduction",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
