# Generated by Django 5.0.1 on 2024-12-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0005_remove_orderartwork_quantity_and_more"),
        ("gallery", "0008_remove_artwork_is_replica_available_and_more"),
        ("store", "0005_remove_basketitem_artwork_remove_basket_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="basket",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket",
                to="store.basket",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderartwork",
            name="artwork",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_artworks",
                to="gallery.artwork",
            ),
        ),
    ]
