# Generated by Django 4.1.6 on 2023-02-25 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_advatage_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advatage',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages_test', to='school.school'),
        ),
    ]
