# Generated by Django 4.1.6 on 2023-02-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_advatage_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advatage',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='school.school'),
        ),
    ]
