# Generated by Django 4.1.6 on 2023-02-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_advatage_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approach', to='school.school'),
        ),
        migrations.AddField(
            model_name='question',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='school.school'),
        ),
        migrations.AddField(
            model_name='review',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='school.school'),
        ),
    ]
