# Generated by Django 4.1.6 on 2023-06-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_school_logo_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='full_description',
            field=models.TextField(max_length=500),
        ),
    ]
