# Generated by Django 4.1.6 on 2023-06-24 06:00

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_school_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='full_description',
            field=mdeditor.fields.MDTextField(max_length=500),
        ),
    ]
