# Generated by Django 4.1.6 on 2023-09-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0015_review_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
