# Generated by Django 4.1.6 on 2023-09-09 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0016_alter_review_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="school",
        ),
    ]
