# Generated by Django 3.2.16 on 2022-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_consent_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consent_comm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='consent_general',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
