# Generated by Django 4.1.6 on 2023-02-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='consent_comm',
            new_name='consent_markcomm',
        ),
        migrations.AlterField(
            model_name='user',
            name='consent_general',
            field=models.BooleanField(null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_user'),
        ),
    ]
