# Generated by Django 4.1.6 on 2023-02-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_agreement_general_user_general_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_nickname',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
