# Generated by Django 4.1.6 on 2023-08-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Post`s title", max_length=80)),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Post`s title", max_length=150
                    ),
                ),
                (
                    "add_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Publication date"
                    ),
                ),
                ("image", models.ImageField(default=None, upload_to="blog/")),
            ],
            options={
                "ordering": ["-add_date"],
            },
        ),
    ]
