# Generated by Django 4.1.6 on 2023-09-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(default=None, upload_to="gallery/"),
        ),
    ]
