# Generated by Django 5.0.1 on 2024-10-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_galleryimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(help_text="Author`s name", max_length=50)),
                (
                    "author_type",
                    models.CharField(
                        choices=[("student", "student"), ("teacher", "teacher")],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(help_text="artwork`s title", max_length=80)),
                (
                    "add_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Publication date"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price might be empty. if so,the artwork is not for sale",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        help_text="dimentions of theartwork in format length x width(if applicable) x height",
                        max_length=50,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        help_text="Material of the artwork",
                        max_length=50,
                        verbose_name="Material",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="artwork`s description", max_length=150
                    ),
                ),
            ],
            options={
                "ordering": ["-add_date"],
            },
        ),
        migrations.CreateModel(
            name="ArtworkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default=None, upload_to="gallery/")),
                (
                    "artwork",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="gallery.artwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artwork Image",
                "verbose_name_plural": "Artwork Images",
            },
        ),
        migrations.DeleteModel(
            name="GalleryImage",
        ),
    ]
