# Generated by Django 5.0.1 on 2024-10-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_artwork_artworkimage_delete_galleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="is_in_stock",
            field=models.BooleanField(
                default="True", verbose_name="is this artwork available"
            ),
            preserve_default=False,
        ),
    ]
