# Generated by Django 5.0.1 on 2024-10-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_artwork_is_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="is_replica_available",
            field=models.BooleanField(
                default=False, verbose_name="is this artwork can be made again"
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="is_in_stock",
            field=models.BooleanField(
                default=True, verbose_name="is this artwork available"
            ),
        ),
    ]
