# Generated by Django 5.0.1 on 2025-01-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_artwork_is_replica_available_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyArtwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                (
                    "author_type",
                    models.CharField(
                        choices=[("student", "student"), ("teacher", "teacher")],
                        max_length=15,
                    ),
                ),
                ("image", models.ImageField(default=None, upload_to="artworks/")),
                ("is_for_sale", models.BooleanField()),
                ("price", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="ArtworkMainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_ordering", models.PositiveSmallIntegerField()),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks_on_main",
                        to="gallery.legacyartwork",
                    ),
                ),
            ],
        ),
    ]
