# Generated by Django 5.0.1 on 2024-11-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0006_legacyartwork_artworkmainpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artworkimage",
            name="artwork",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="images",
                to="gallery.artwork",
            ),
            preserve_default=False,
        ),
    ]
