# Generated by Django 5.0.1 on 2024-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0007_alter_artworkimage_artwork"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="is_replica_available",
        ),
        migrations.AddField(
            model_name="artwork",
            name="is_reproducible",
            field=models.BooleanField(
                default=False,
                verbose_name="is this artwork can be made again (is_reproducible)",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="reproduction_estimation_in_days",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="ask the management for an estimation if the numberis not provided by this point",
                verbose_name="The calendar days estimation to recreate the artwork",
            ),
        ),
    ]
