# Generated by Django 4.1.6 on 2023-06-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_alter_post_options_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='blog.PostTag', to='blog.tag'),
        ),
    ]
