# Generated by Django 4.1.6 on 2023-07-24 04:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_rename_tag_tag_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Publication date"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="read_time",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Approximate time that is reqired to read the article",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(
                help_text="defines an address where users can acess this post, for instance, ifthe slug is <mosaic>, the post will beaccesible at blog/mosaic",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(help_text="Post`s title", max_length=80),
        ),
        migrations.AlterField(
            model_name="posttag",
            name="post",
            field=models.ForeignKey(
                help_text="choose to what post to add a tag",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.post",
            ),
        ),
        migrations.AlterField(
            model_name="posttag",
            name="tag",
            field=models.ForeignKey(
                help_text="choose what tag to add to a post you choose above",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="blog.tag",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(
                help_text="defines a name for the searchfield", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(help_text="how the tag is named", max_length=50),
        ),
    ]
