# Generated by Django 4.1.6 on 2023-08-02 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_post_pub_date_alter_post_read_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="upd_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Update date",
            ),
            preserve_default=False,
        ),
    ]
