# Generated by Django 4.1.6 on 2023-08-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_post_upd_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(
                help_text="defines an address where users can acess this post, for instance, ifthe slug is <mosaic>, the post will beaccesible at blog/mosaic",
                max_length=80,
                unique=True,
            ),
        ),
    ]
