# Generated by Django 4.1.6 on 2023-08-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default=None, upload_to="blog/"),
        ),
    ]
