# Generated by Django 4.1.3 on 2022-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='num_of_guests',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
