# Generated by Django 4.1.6 on 2023-02-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterclass',
            options={'verbose_name': 'Masterclass', 'verbose_name_plural': 'Masterclasses'},
        ),
        migrations.AlterModelOptions(
            name='masterclasstype',
            options={'ordering': ['id'], 'verbose_name': 'Masterclass type', 'verbose_name_plural': 'Masterclass types'},
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='time_begin',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='course_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='masterclasses', to='masterclass.masterclasstype'),
            preserve_default=False,
        ),
    ]
