# Generated by Django 4.1.3 on 2022-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0002_masterclass_num_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclasstype',
            name='length',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='How many hours required to finish masterclass'),
            preserve_default=False,
        ),
    ]
