# Generated by Django 4.1.3 on 2022-11-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0004_alter_masterclass_time_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
