# Generated by Django 4.1.3 on 2022-11-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0005_masterclass_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='title',
            field=models.CharField(default='masterclass', max_length=50, verbose_name='Title'),
        ),
    ]
