# Generated by Django 4.1.6 on 2023-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0007_remove_masterclass_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='num_of_guests',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
