# Generated by Django 4.1.3 on 2022-11-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0007_masterclass_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterclasstype',
            old_name='title',
            new_name='type',
        ),
    ]
