# Generated by Django 4.1.3 on 2022-11-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0008_rename_title_masterclasstype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterclasses', to='masterclass.masterclasstype'),
        ),
    ]
