# Generated by Django 4.1.6 on 2023-02-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0010_remove_masterclass_num_of_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterclasstype',
            old_name='length',
            new_name='duration',
        ),
    ]
