# Generated by Django 4.1.6 on 2023-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_general_agreement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "user"), ("admin", "admin"), ("teacher", "teacher")],
                default="user",
                max_length=32,
            ),
        ),
    ]
