# Generated by Django 4.1.6 on 2023-08-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("phone", "email"), name="unique_user"
            ),
        ),
    ]
