# Generated by Django 4.1.6 on 2023-08-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_unique_user_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="general_agreement",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="markcomm_agreement",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
