# Generated by Django 4.1.6 on 2023-08-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="times_postponed",
            field=models.SmallIntegerField(default=0),
        ),
    ]
